### PR TITLE
More LaTeX docstring formatting + fix typos in `RoquetSeawaterPolynomial` docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by navidcy** [comment]
@glwagner so in the docs in a few places there were terms like `R₁₀₀ * Θ` or `R₀₁₀ * Sᴬ` while from what I understand they should be `R₀₁₀ * Θ` and `R₁₀₀ * Sᴬ`, since the first subscript of R refers to S and second to Θ. I fixed them. But I'm wondering if the mistakes are in the code as well...

**Comment by navidcy** [comment]
> @glwagner so in the docs in a few places there were terms like `R₁₀₀ * Θ` or `R₀₁₀ * Sᴬ` while from what I understand they should be `R₀₁₀ * Θ` and `R₁₀₀ * Sᴬ`, since the first subscript of R refers to S and second to Θ. I fixed them. But I'm wondering if the mistakes are in the code as well...

From what I see the code is ok.

**Comment by navidcy** [comment]
Another question: is Θ expected in degrees C or degrees K?

**Review by glwagner — APPROVED** [review]
<3

**Comment by glwagner** [comment]
> Another question: is Θ expected in degrees C or degrees K?

I believe C

**Comment by glwagner** [comment]
> > @glwagner so in the docs in a few places there were terms like `R₁₀₀ * Θ` or `R₀₁₀ * Sᴬ` while from what I understand they should be `R₀₁₀ * Θ` and `R₁₀₀ * Sᴬ`, since the first subscript of R refers to S and second to Θ. I fixed them. But I'm wondering if the mistakes are in the code as well...
> 
> From what I see the code is ok.

Oh! I can't remember the system but yes, there is a system defined in the Roquet paper and we should follow that

**Pull request merged**
